// <auto-generated />
using GrpcGreeter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrpcGreeter.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20220801160156_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GrpcGreeter.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Ann",
                            LastName = "Fox",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Sam",
                            LastName = "Deo",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Sue",
                            LastName = "Cox",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Tim",
                            LastName = "Lee",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "Jan",
                            LastName = "Ray",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 6,
                            FirstName = "Ashish",
                            LastName = "Hatkar",
                            School = "Software"
                        },
                        new
                        {
                            StudentId = 7,
                            FirstName = "Bhargav",
                            LastName = "Hatkar",
                            School = "Schooling"
                        },
                        new
                        {
                            StudentId = 8,
                            FirstName = "Saee",
                            LastName = "Hatkar",
                            School = "Mothering"
                        },
                        new
                        {
                            StudentId = 9,
                            FirstName = "Leena",
                            LastName = "Hatkar",
                            School = "Banking"
                        },
                        new
                        {
                            StudentId = 10,
                            FirstName = "Janu",
                            LastName = "KH",
                            School = "Colleging"
                        },
                        new
                        {
                            StudentId = 11,
                            FirstName = "Test",
                            LastName = "Test",
                            School = "Testing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
